version: 1
disable_existing_loggers: False

loggers:
    multivimbroker:
      handlers: [multivimbroker_handler]
      level: "DEBUG"
      propagate: False
handlers:
    multivimbroker_handler:
        level: "DEBUG"
        class: "logging.handlers.RotatingFileHandler"
        filename: "/var/log/onap/multicloud/multivimbroker/multivimbroker.log"
        formatter: "standard"
        maxBytes: 52428800
        backupCount: 10
formatters:
    standard:
        format: "%(asctime)s|||||%(name)s||%(thread)||%(funcName)s||%(levelname)s||%(message)s"
